#!/bin/sh

KB_LEDS=/dev/input/event0
EV_LED="\x00\x11"
LED_NUML="\x00\x00"
LED_CAPSL="\x00\x01"
LED_SCROLLL="\x00\x02"
TURN_ON="\x00\x00\x00\x01"
TURN_OFF="\x00\x00\x00\x00"
DT_DUMMY="\x00\x00\x00\x00\x00\x00\x00\x00"

NUM_ON=$DT_DUMMY$EV_LED$LED_NUML$TURN_ON
NUM_OFF=$DT_DUMMY$EV_LED$LED_NUML$TURN_OFF
CAPS_ON=$DT_DUMMY$EV_LED$LED_CAPSL$TURN_ON
CAPS_OFF=$DT_DUMMY$EV_LED$LED_CAPSL$TURN_OFF
SCROLL_ON=$DT_DUMMY$EV_LED$LED_SCROLLL$TURN_ON
SCROLL_OFF=$DT_DUMMY$EV_LED$LED_SCROLLL$TURN_OFF

if ! ps | grep -qe "[c]at $KB_LEDS"; then  cat $KB_LEDS > /dev/null & fi

if [ -z "$QUERY_STRING" ]; then COMMAND=$1;
else
COMMAND=`echo "$QUERY_STRING" | sed -n 's/^.*command=\([^&]*\).*$/\1/p'`
printf "Content-type: text/plain\r\n\r\n"
fi

case $COMMAND in
        num_on)
                printf $NUM_ON  > $KB_LEDS;;
        num_off)
                printf $NUM_OFF > $KB_LEDS;;
        caps_on)
        	printf caps_on > /var/rrr
                printf $CAPS_ON > $KB_LEDS;;
                
        caps_off)
        	printf caps_off > /var/rrr
                printf $CAPS_OFF > $KB_LEDS;;
        scroll_on)
                printf $SCROLL_ON > $KB_LEDS;;
        scroll_off)
                printf $SCROLL_OFF > $KB_LEDS;;
        num_pulse)
                printf $NUM_ON  > $KB_LEDS
                sleep 1
                printf $NUM_OFF > $KB_LEDS
                ;;
        caps_pulse)
                printf $CAPS_ON > $KB_LEDS
                sleep 1
                printf $CAPS_OFF > $KB_LEDS
                ;;
        scroll_pulse)
                printf $SCROLL_ON > $KB_LEDS
                sleep 1
                printf $SCROLL_OFF > $KB_LEDS
                ;;
        *)      WRONG_ARG=1;;
esac

if [ -z $WRONG_ARG ]
then
        STATE_FILE=/var/ledstate
        DEFAULT_STATE={\"num\":false,\"caps\":false,\"scroll\":false}
        if ! [ -e $STATE_FILE ]; then  echo $DEFAULT_STATE > $STATE_FILE; fi
        AFFECTED_LED=`echo $COMMAND | sed -r -e 's/_[a-z]+$//'`
        NEW_STATE=`echo $COMMAND | sed -r -e 's/^[a-z]+_//' -e 's/on/true/' -e 's/off|pulse/false/'`
        sed -i -r 's/"'"$AFFECTED_LED"'":[a-z]+/"'"$AFFECTED_LED"'":'"$NEW_STATE"'/' $STATE_FILE
fi

